### ISSUE TITLE
query error: no field 'name' found in schema

### ISSUE THREAD

**Issue by dwickwire** [pat/thinking-sphinx#977]
Hello, I'm upgrading an old Rails 2.3 app and started by upgrading Ruby so its currently still on Rails 2.3.  I can't jump to a nice modern version of TS so I'm trying to use various versions of TS (currently at 1.5.0) to find which one will work.  Is that compatible with Sphinx 2.0.4?  

Here's my index
```ruby
class Customer < ActiveRecord::Base
  #...
  set_sphinx_primary_key :unique_id
  define_index 'customer_location' do
    # ..
    indexes name
    #...
    has :unique_id
    where "LEFT(location_id, 1) = 'C'"
  end
  #...
end
```

Conf
```conf
source customer_location_core_0
{
  type = mysql
  sql_host = localhost
  sql_user = myuser
  sql_pass = mypass
  sql_db = mydb
  sql_query_pre = SET NAMES utf8
  sql_query_pre = SET TIME_ZONE = '+0:00'
  sql_query = SELECT SQL_NO_CACHE `customer_locations`.`unique_id` * CAST(2 AS SIGNED) + 0 AS `unique_id` , `customer_locations`.`id` AS `gnp_number`, `customers`.`customer_category` AS `category`, `customers`.`customer_type` AS `type`, `customer_locations`.`name` AS `name`, `customer_locations`.`address` AS `address`, `customer_locations`.`city` AS `city`, `customer_locations`.`state` AS `state`, `customer_locations`.`zip` AS `zip`, `customer_locations`.`country` AS `country`, `customer_locations`.`phone` AS `phone`, `customer_locations`.`email` AS `email`, `customer_locations`.`location_type` AS `location_type`, `customer_locations`.`unique_id` AS `sphinx_internal_id`, 0 AS `sphinx_deleted`, 3500016976 AS `class_crc`, IFNULL('CustomerLocation', '') AS `sphinx_internal_class`, `customer_locations`.`unique_id` AS `unique_id` FROM `customer_locations`    LEFT OUTER JOIN `customers` ON `customers`.id = `customer_locations`.id  WHERE `customer_locations`.`unique_id` >= $start AND `customer_locations`.`unique_id` <= $end AND LEFT(location_id, 1) = 'C' GROUP BY `customer_locations`.`unique_id`  ORDER BY NULL
  sql_query_range = SELECT IFNULL(MIN(`unique_id`), 1), IFNULL(MAX(`unique_id`), 1) FROM `customer_locations` 
  sql_attr_uint = sphinx_internal_id
  sql_attr_uint = sphinx_deleted
  sql_attr_uint = class_crc
  sql_attr_uint = unique_id
  sql_attr_string = sphinx_internal_class
  sql_query_info = SELECT * FROM `customer_locations` WHERE `unique_id` = (($id - 0) / 2)
}
```

When I'm searching I keep getting this error

```ruby
model.search({conditions: {name: "John"}})
> query error: no field 'name' found in schema
```

It doesn't matter which attribute I search with either, they all throw this error.  Is this a TS version incompatibility with Sphinx 2.0.4?

**Comment by pat** [comment]
I would expect TS v1.5 to be okay with Sphinx 2.0.4 (certainly I would not recommend 2.1.x or newer releases, though!).

When you run `rake ts:stop`, can you confirm that there are no running `searchd` processes via `ps aux | grep searchd`? And then run `rake ts:index ts:start` and share the output here if the problem persists?

**Comment by dwickwire** [comment]
Pat, first let me say how awesome I think it is that you're still supporting thinking-sphinx, so many years into it.  A big thanks for that!

As for the results of what you asked:

#### $ rake ts:stop

```shell
Stopped search daemon (pid 2399).
myapp@vagrant:/opt/rails/myapp/current$ ps aux | grep search
myapp  2591  0.0  0.0  10460   940 pts/0    S+   14:49   0:00 grep --color=auto search
```

#### $ rake ts:index ts:start

```shell
Generating Configuration to /opt/rails/myapp/current/config/development.sphinx.conf
Sphinx 2.0.4-id64-release (r3135)
Copyright (c) 2001-2012, Andrew Aksyonoff
Copyright (c) 2008-2012, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/opt/rails/myapp/current/config/development.sphinx.conf'...
indexing index 'customer_location_core'...
WARNING: collect_hits: mem_limit=0 kb too low, increasing to 26368 kb
collected 324146 docs, 34.5 MB
sorted 5.2 Mhits, 100.0% done
total 324146 docs, 34456679 bytes
total 4.887 sec, 7050294 bytes/sec, 66324.58 docs/sec
skipping non-plain index 'customer_location'...
indexing index 'customer_location_partial_core'...
WARNING: collect_hits: mem_limit=0 kb too low, increasing to 26368 kb
collected 324146 docs, 2.5 MB
sorted 4.7 Mhits, 100.0% done
total 324146 docs, 2452115 bytes
total 4.172 sec, 587668 bytes/sec, 77684.13 docs/sec
skipping non-plain index 'customer_location_partial'...
indexing index 'order_core'...
WARNING: collect_hits: mem_limit=0 kb too low, increasing to 26368 kb
collected 218132 docs, 32.5 MB
sorted 4.7 Mhits, 100.0% done
total 218132 docs, 32546503 bytes
total 10.651 sec, 3055545 bytes/sec, 20478.76 docs/sec
skipping non-plain index 'order'...
indexing index 'partial_matching_core'...
WARNING: collect_hits: mem_limit=0 kb too low, increasing to 26368 kb
collected 218132 docs, 9.6 MB
sorted 29.3 Mhits, 100.0% done
total 218132 docs, 9640467 bytes
total 22.884 sec, 421264 bytes/sec, 9531.82 docs/sec
skipping non-plain index 'partial_matching'...
total 385 reads, 3.003 sec, 1238.2 kb/call avg, 7.8 msec/call avg
total 1262 writes, 6.985 sec, 690.5 kb/call avg, 5.5 msec/call avg
Started successfully (pid 2631).
```


#### server log during request
```sql
  Sphinx   Querying: '@name Joe Smith'
  Sphinx (0.045925s)   Found  results
  Sphinx   Sphinx Daemon returned error: query error: no field 'name' found in schema
  Sphinx   Caught Sphinx exception: query error: no field 'name' found in schema (0 tries left)

ThinkingSphinx::SphinxError (query error: no field 'name' found in schema):
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thinking-sphinx-1.5.0/lib/thinking_sphinx/search.rb:435:in `block in populate'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thinking-sphinx-1.5.0/lib/thinking_sphinx/search.rb:603:in `call'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thinking-sphinx-1.5.0/lib/thinking_sphinx/search.rb:603:in `retry_on_stale_index'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thinking-sphinx-1.5.0/lib/thinking_sphinx/search.rb:419:in `populate'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thinking-sphinx-1.5.0/lib/thinking_sphinx/search.rb:172:in `method_missing'
  app/models/gnpcb/customer_location.rb:175:in `block in calculate'
  app/models/gnpcb/customer_location.rb:167:in `each'
  app/models/gnpcb/customer_location.rb:167:in `calculate'
  app/models/gnpcb/customer_location.rb:156:in `locate'
  app/models/gnpcb/customer_location.rb:121:in `matches'
  app/models/gnpcb/acumen_customer.rb:22:in `match_search'
  app/models/order.rb:169:in `match_search'
  app/controllers/processes_controller.rb:47:in `display'
  lib/authenticated_system.rb:70:in `catch_unauthorized'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.5.5.38/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:270:in `block in perform_action_with_newrelic_trace'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.5.5.38/lib/new_relic/agent/method_tracer.rb:240:in `trace_execution_scoped'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.5.5.38/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:263:in `perform_action_with_newrelic_trace'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.5.5.38/lib/new_relic/rack/browser_monitoring.rb:12:in `call'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.5.5.38/lib/new_relic/rack/developer_mode.rb:24:in `call'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /home/myapp/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

Rendered rescues/_trace (10.6ms)
Rendered rescues/_request_and_response (0.5ms)
Rendering rescues/layout (internal_server_error)
```

**Comment by pat** [comment]
Looks like you've got multiple indices for `CustomerLocation` - does the field `name` exist in both index definitions?

If not, in TS v1/v2 you can specify which indices to search on using the `:index` option (which expects a string - multiple index names should be separated by just a comma) so perhaps give that a shot?

**Comment by pat** [comment]
Also: thanks for the kind words. It's been almost nine years since I started Thinking Sphinx - perhaps I should organise a cake for next year! :)

**Comment by dwickwire** [comment]
A cake sounds appropriate indeed :)

There is another index but its just a `customer_location_partial` index.  Actually, I'm already using the `:index` option in the app too, but not in the example above.  Hm.

Perhaps I just need to upgrade Rails together with Ruby then.  It had to happen eventually anyway, I was just hoping to iterate to it.

**Comment by pat** [comment]
New idea: can you try `indexes :name` instead of `indexes name`? I'd forgotten that old versions of Ruby (and/or possibly Rake) add methods to Object that get in the way of method_missing (`id` was certainly one, and maybe `name` is another). So maybe that's the cause of the problem?

Although now that I've typed that idea out, I can see that `name` is appearing in the sql_query statement… so, probably not going to change anything at all, but maybe it's worth a shot?

To be honest, I'm really at a loss with this. The configuration is right, there's nothing odd in the Sphinx output from indexing… perhaps the output from starting it manually may hold a clue? Run `rake ts:stop`, but then try `searchd --config config/development.sphinx.conf --pidfile` to get it running again, and let me know what the output of that command is…

**Comment by dwickwire** [comment]
Incidentally before my ruby upgrade I did have `indexes :name`, I must have switched that in the example code above from my debugging.  

Also interesting:  It seems to search with my existing code with Ruby 1.9.3. but not with 2.1.2 on Rails 2.3.  I should've mentioned this up front, but did have to add a few [necessary monkey patches](https://gist.github.com/dwickwire/b3d8ffb3369743b4e2648b9e8b5c47af) to use Ruby 2.1.2. with Rails 2.3 but I'm not sure if that would affect anything with thinking-sphinx.

Here's the output of the command after a `rake ts:stop`:

#### $ searchd --config config/development.sphinx.conf --pidfile
```shell
Sphinx 2.0.4-id64-release (r3135)
Copyright (c) 2001-2012, Andrew Aksyonoff
Copyright (c) 2008-2012, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file 'config/development.sphinx.conf'...
WARNING: compat_sphinxql_magics=1 is deprecated; please update your application and config
listening on 127.0.0.1:9312
precaching index 'acumen_customer_location_core'
precaching index 'acumen_customer_location_partial_core'    
precaching index 'order_core'                               
precaching index 'partial_matching_core'                    
precached 4 indexes in 29.579 sec     
```

Still end up with the `query error: no field 'name' found in schema)` though.

**Comment by dwickwire** [comment]
Just a point of clarification, it worked with Ruby 1.9.3 and Rake 10.4.2 but not with rake 11.1.2.  Weird.

**Comment by dwickwire** [comment]
I can iterate to a higher version of Rails from 1.9.3, so I'll just close this issue and if I get any more info about the ruby 2.1.2 details I'll leave my notes here.  Thanks for the help, Pat!

**Comment by pat** [comment]
No worries! Hope the upgrade isn't too painful :)
