### ISSUE TITLE
All searches return (Object doesn't support #inspect) after upgrading from 2.1.x to 3.1.4

### ISSUE THREAD

**Issue by danielsettanni** [pat/thinking-sphinx#949]
Hello,

I just upgraded thinking-sphinx from 2.1.x to 3.1.4, and re-indexed without any issues, however now I cannot retrieve any results, with all searches yielding (Object doesn't support #inspect).

I've found a number of references to this error which appears to be related to the mysql2 library version though I believe I am using the recommended version.

I'm using Sphinx version 2.2.10 (Sphinx 2.2.10-id64-release (2c212e0))

I have the following defined in my gemfile related to thinking-sphinx:
gem 'thinking-sphinx', '~> 3.1.0'
gem 'ts-delayed-delta', '~> 2.0.2'
gem 'mysql2',          '~> 0.3.18', :platform => :ruby
gem 'delayed_job_active_record'

Here's the output from bundle listing the specific versions installed:
bundle
...
Using delayed_job_active_record 4.0.3
Using mysql2 0.3.20
Using thinking-sphinx 3.1.4
Using ts-delayed-delta 2.0.2

Here's the output from a basic search:
City.search('New Milford, CT')
(Object doesn't support #inspect)
 =>  

Here's what I get by adding .to_a
City.search('New Milford, CT').to_a
NoMethodError: undefined method `inject' for nil:NilClass
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/middlewares/inquirer.rb:49:in `call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/middlewares/inquirer.rb:14:in `block in call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/middlewares/inquirer.rb:13:in `each'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/middlewares/inquirer.rb:13:in `call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/middlewares/geographer.rb:11:in `call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/middlewares/sphinxql.rb:14:in `call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/middlewares/stale_id_filter.rb:10:in `call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/search.rb:67:in `populate'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/search.rb:91:in `to_a'
	from (irb):2
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.22/lib/rails/commands/console.rb:47:in `start'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.22/lib/rails/commands/console.rb:8:in `start'
	from /Users/daniel/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.22/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'

Also, sphinx's search command does retrieve results successfully for all indexes:
search -c config/development.sphinx.conf 
using config file 'config/development.sphinx.conf'...
index 'city_core': query '': returned 1000 matches of 2564934 total in 0.062 sec

displaying matches:
1. document=1033533, weight=1, full_name=Xixerella, full_name_nd=Xixerella, adm1_full_name=Parròquia de la Massana, adm1_code=04, adm2_full_name=, adm2_code=, cc_iso=AD, sort_name=XIXERELLA, sphinx_internal_id=38279, sphinx_internal_class=City, sphinx_deleted=0, id=38279, uni=80500001, weight=0, lat=0.742695, lng=0.025959
2. document=1033560, ....

Here's my city index definition:
ThinkingSphinx::Index.define(:city, :with => :active_record, :delta => ThinkingSphinx::Deltas::DelayedDelta) do
  indexes full_name, full_name_nd, adm1_full_name, adm1_code, adm2_full_name, adm2_code, cc_iso, sort_name, :sortable => true
  indexes country(:country_name), :as => :country_name
  indexes city_aliases(:alias_name), :as => :alias
  has :id
  has :uni
  has :weight
  has "RADIANS(latitude)",  :as => :lat,  :type => :float
  has "RADIANS(longitude)", :as => :lng, :type => :float
end

I'm sure I'm missing something stupid, but seem to have hit a dead end on what to look at next.

Any suggestions would be appreciated,
Thanks!
 - Daniel

**Comment by pat** [comment]
Did you get this one sorted? Sounds like Sphinx may have not been compiled with mysql support?

**Comment by danielsettanni** [comment]
No, unfortunately didn't figure it out.  I put in some rough logging around where the the exception was being thrown and found that the results were being retrieved.

Here's a snippet:
ThinkingSphinx::Middlewares::StaleIdFilter.call first context [#<ThinkingSphinx::Search::Context:0x007fb3d10e1578 @search=[{"id"=>2398812, "weight"=>55907, "full_name"=>"Milford", "full_name_nd"=>"Milford", "adm1_full_name"=>"Connecticut", "adm1_code"=>"CT", "adm2_full_name"=>"New Haven County", "adm2_code"=>"009", "cc_iso"=>"US", "sort_name"=>"MILFORD", "sphinx_internal_id"=>2398812, "sphinx_internal_class"=>"City", "sphinx_deleted"=>0, "uni"=>82860534, "lat"=>0.719465, "lng"=>-1.275077}, {"id"=>2398870, "weight"=>28338, "full_name"=>"New Milford", "full_name_nd"=>"New Milford", "adm1_full_name"=>"Connecticut", "adm1_code"=>"CT", "adm2_full_name"=>"Litchfield County", "adm2_code"=>"005", "cc_iso"=>"US", "sort_name"=>"NEWMILFORD", "sphinx_internal_id"=>2398870, "sphinx_internal_class"=>"City", "sphinx_deleted"=>0, "uni"=>82860592, "lat"=>0.725656, "lng"=>-1.281219}, {"id"=>2398813, "weight"=>0, "full_name"=>"Milford Lawns", "full_name_nd"=>"Milford Lawns", "adm1_full_name"=>"Connecticut", "adm1_code"=>"CT", "adm2_full_name"=>"New Haven County", "adm2_code"=>"009", "cc_iso"=>"US", "sort_name"=>"MILFORDLAWNS", "sphinx_internal_id"=>2398813, "sphinx_internal_class"=>"City", "sphinx_deleted"=>0, "uni"=>82860535, "lat"=>0.719509, "lng"=>-1.274223}], @configuration=#<ThinkingSphinx::Configuration:0x007fb3d489f848 @common=#<Riddle::Configuration::Common:0x007fb3d489f820>, @indexer=#<Riddle::Configuration::Indexer:0x007fb3d489f7f8 @mem_limit="2048M">, @searchd=#<Riddle::Configuration::Searchd:0x007fb3d489f7d0 @pid_file="/development/ruby/rails/pre_pilot/proto_postgres/log/development.sphinx.pid", @log="/development/ruby/rails/pre_pilot/proto_postgres/log/development.searchd.log", @query_log="/development/ruby/rails/pre_pilot/proto_postgres/log/development.searchd.query.log", @binlog_path="/development/ruby/rails/pre_pilot/proto_postgres/tmp/binlog/development", @address="127.0.0.1", @mysql41=9312, @workers="threads", @max_matches=2000>, @indices=[#<ThinkingSphinx::ActiveRecord::Index:0x007fb3d0df8d48 @reference=:city, @docinfo=:extern, @options={:with=>:active_record, :delta?=>false, :delta_processor=>ThinkingSphinx::Deltas::DelayedDelta}, @offset=0, @type="plain", @name="city_core"....

ThinkingSphinx::Middlewares::StaleIdFilter.call caught exception #<NoMethodError: undefined method `new?' for #<Mysql2::Result:0x007fb3d1e42230>>
 => [{"id"=>2398812, "weight"=>55907, "full_name"=>"Milford", "full_name_nd"=>"Milford", "adm1_full_name"=>"Connecticut", "adm1_code"=>"CT", "adm2_full_name"=>"New Haven County", "adm2_code"=>"009", "cc_iso"=>"US", "sort_name"=>"MILFORD", "sphinx_internal_id"=>2398812, "sphinx_internal_class"=>"City", "sphinx_deleted"=>0, "uni"=>82860534, "lat"=>0.719465, "lng"=>-1.275077}, {"id"=>2398870, "weight"=>28338, "full_name"=>"New Milford", "full_name_nd"=>"New Milford", "adm1_full_name"=>"Connecticut", "adm1_code"=>"CT", "adm2_full_name"=>"Litchfield County", "adm2_code"=>"005", "cc_iso"=>"US", "sort_name"=>"NEWMILFORD", "sphinx_internal_id"=>2398870, "sphinx_internal_class"=>"City", "sphinx_deleted"=>0, "uni"=>82860592, "lat"=>0.725656, "lng"=>-1.281219}, {"id"=>2398813, "weight"=>0, "full_name"=>"Milford Lawns", "full_name_nd"=>"Milford Lawns", "adm1_full_name"=>"Connecticut", "adm1_code"=>"CT", "adm2_full_name"=>"New Haven County", "adm2_code"=>"009", "cc_iso"=>"US", "sort_name"=>"MILFORDLAWNS", "sphinx_internal_id"=>2398813, "sphinx_internal_class"=>"City", "sphinx_deleted"=>0, "uni"=>82860535, "lat"=>0.719509, "lng"=>-1.274223}]

**Comment by danielsettanni** [comment]
continued...

That's as far as I got. 

I'm guessing it had something to do with the mysql2 gem but since TS 2.x is working well and this wasn't a critical upgrade for us we had to move on to other things for now. 

Thanks for the follow up and the awesome software!
 - Daniel

**Comment by pat** [comment]
No worries - shame it wasn't resolved, but if/when you do go down this upgrade path again, I'd recommend the next step to be recompiling Sphinx and explicitly request both MySQL and PostgreSQL support (I'm guessing you're using PostgreSQL as your database) and see if that helps.

**Comment by danielsettanni** [comment]
Excellent, thank you for the advice.  I do use Postgres and while I noticed output from configure indicated that mysql was detected, I didn’t specifically enable it so perhaps it wasn’t actually compiled in.  Will check that out the next time I attempt the upgrade.

Thanks again,
Daniel

On Sep 15, 2015, at 2:31 PM, Pat Allan <notifications@github.com> wrote:

No worries - shame it wasn't resolved, but if/when you do go down this upgrade path again, I'd recommend the next step to be recompiling Sphinx and explicitly request both MySQL and PostgreSQL support (I'm guessing you're using PostgreSQL as your database) and see if that helps.
