### ISSUE TITLE
TS 3.0.5 search_for_ids on scope results in method missing

### ISSUE THREAD

**Issue by kayleg** [pat/thinking-sphinx#628]
This was working in 2.0.14
But now I get a method missing instead with latest gem and master

```
sphinx_scope(:published) { 
  { :with => { published: true } } 
}
```

`Article.published` returns an array of articles
`Article.search_for_ids` returns array of ids
`Article.published.search_for_ids` => 'NoMethodError: undefined method `search_for_ids' for #Array:0x007ff0b8162960' 

`Article.published.class = ThinkingSphinx::Search`
