### ISSUE TITLE
thinking sphinx rebuild task doesn't work in rails 3.0.3

### ISSUE THREAD

**Issue by pacoguzman** [pat/thinking-sphinx#158]
Hi,

After upgrade to rails 3.0.3 when I execute: rake ts:rebuild I got the following error

undefined method `with_join_class' for #ActiveRecord::Associations::ClassMethods::JoinDependency::JoinAssociation:0x000000045ccde0

/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/association.rb:67:in `arel_join'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/source/sql.rb:23:in`block in to_sql'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/source/sql.rb:22:in `each'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/source/sql.rb:22:in`to_sql'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/source.rb:103:in `set_source_sql'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/source.rb:50:in`to_riddle_for_core'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/index.rb:114:in `block in to_riddle_for_core'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/index.rb:113:in`each'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/index.rb:113:in `each_with_index'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/index.rb:113:in`to_riddle_for_core'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/index.rb:83:in `to_riddle'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/active_record.rb:223:in`block in to_riddle'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/active_record.rb:222:in `collect'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/active_record.rb:222:in`to_riddle'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/configuration.rb:155:in `block in build'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/configuration.rb:152:in`each'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/configuration.rb:152:in `build'
/home/pacoguzman/.rvm/gems/ruby-1.9.2-p0/gems/thinking-sphinx-2.0.0/lib/thinking_sphinx/tasks.rb:76:in`block (2 levels) in <top (required)>'
